name: 'CI'

env:
  BUILD_NUMBER: '1970.1.1'
  asset_directory: '${{github.workspace}}\build\'

on:
  push:
    branches: 
      - features/*
      - fixes/*

jobs:
  build:
    name: 'Build openHAB Windows App'
    runs-on: windows-latest

    steps:
    - name: Checkout master code
      uses: actions/checkout@v2
      with:
        path: src
        clean: true 

    - name: Build App
      id: create_app_package
      uses: ./.github/workflows/actions/app-build
      with:
        build_configuration: 'release'
        ouput_directory: ${{env.asset_directory}}